version: '3.8'
services:
  nginx:
    container_name: nginx
    build:
      context: ./infra/docker/nginx
      dockerfile: Dockerfile
    ports:
      - ${WEB_PORT}:80
    tty: true
    restart: always
    depends_on:
      - web

  web:
    container_name: web
    build:
      context: ./infra/docker/web
      dockerfile: Dockerfile
    environment:
      PORT: ${FRONT_PORT}
      HOST: '0.0.0.0'
    expose:
      - ${FRONT_PORT}
    volumes:
      - ./web:/app
    stdin_open: true
    tty: true
    restart: always
    depends_on:
      - api

  api:
    container_name: api
    build:
      context: ./infra/docker/api
      dockerfile: Dockerfile
    environment:
      LANG: 'ja_JP.UTF-8'
      TZ: ${TZ}
      DB_CONNECTION: 'mysql'
      DB_HOST: 'db'
      DB_PORT: '3306'
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      SESSION_DOMAIN: 'localhost'
      SESSION_LIFETIME: ${SESSION_LIFETIME}
      SANCTUM_STATEFUL_DOMAINS: 'localhost'
      SESSION_DRIVER: 'cookie'
    volumes:
      - ./api:/app
    expose:
      - ${API_PORT}
    tty: true
    restart: always
    depends_on:
      - db

  db:
    image: mariadb:10.4
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    volumes:
          - db:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    restart: always

  # testing_db:
  #   image: mariadb:10.4
  #   container_name: testing_db
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${TESTING_MYSQL_DATABASE}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #     TZ: ${TZ}
  #   volumes:
  #         - testing_db:/var/lib/mysql
  #   ports:
  #     - ${TESTING_DB_PORT}:3306

volumes:
  db:
  # testing_db:
