name: Docker Testing

on:
  pull_request:
    paths:
      - 'infra/*'

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Git Clone Project
        run: git clone https://github.com/DaikiKawaoka/webmemo.git src

      - name: Docker Version
        run: docker version

      - name: Build Docker Images
        run: docker compose build
